### ISSUE TITLE
Properties: understanding the proof of subst

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#336]
In chapter Properties, there is a proof that substitution preserves types that starts like this:

```agda
subst : ∀ {Γ x N V A B}
  → ∅ ⊢ V ⦂ A
  → Γ , x ⦂ A ⊢ N ⦂ B
    --------------------
  → Γ ⊢ N [ x := V ] ⦂ B

subst {x = y} ⊢V (⊢` {x = x} Z) with x ≟ y
... | yes refl        =  weaken ⊢V
... | no  x≢y         =  ⊥-elim (x≢y refl)
```

I'd appreciate your help in understanding this case, though I can't understand similar cases following this one either. What I'm failing to understand is what `y` corresponds to in the case above. Is it simply a fresh name for the outer implicit `x`? If so, how can the test in the with clause `x ≟ y` result in anything else than `yes refl`? If not, please explain what is `y`.

This is probably a question that doesn't have much to do with the book, but more with implicit arguments in Agda. I tried understanding this by reading about implicit arguments from [Agda's documentation](https://agda.readthedocs.io/en/v2.5.4.2/language/implicit-arguments.html), but to no avail.

**Comment by h4iku** [comment]
In the first variable case, `N` is term `` ` x ``. So, by `{x = y}` the implicit `x` turns into `y`, and by `{x = x}` the `x` in term `` ` x `` turns into `x`, which results in something like this:

```agda
subst : ∀ {Γ y x V A B}
  → ∅ ⊢ V ⦂ A
  → Γ , y ⦂ A ⊢ ` x ⦂ B
    --------------------
  → Γ ⊢ ` x [ y := V ] ⦂ B
```

now when `x ≟ y` is `yes`, it means that the extended `y` in the context and the `x` in term `` ` x `` are the same (as we expected because of `Z` in the typing judgment `` (⊢` {x = x} Z) ``), and also now `A` and `B` are the same, thus by substituting `V` for `x`, it turns into:

```
∅ ⊢ V ⦂ A
Γ , y ⦂ A ⊢ ` x ⦂ A
-------------------
Γ ⊢ V ⦂ A
```

and using `weaken` on `⊢V` we can get from `∅ ⊢ V ⦂ A` to `Γ ⊢ V ⦂ A`, which is the conclusion we are after.

if `x ≟ y` is `no`, we reach a situation that we are not expecting since `` (⊢` {x = x} Z) `` says that the variable `x` we are looking for is the first one in the context, so it becomes a contradiction.

**Comment by wadler** [comment]
H4aiku is correct, thank you! Marko, suggestions for how to reword to avoid the confusion you suffered would be welcome.

**Comment by mdimjasevic** [comment]
Thank you @h4iku for your explanation and my apologies for a late reply!

The explanation that follows immediately after the proof of `subst` is quite good. Nevertheless, I think the proof can be improved by introducing fresh variable names (instead of `x` and `y`); while they are accepted by Agda, I'd argue that bindings like `{x = x}` are not very pedagogical, even more so when there are two parts of a case that have a hidden argument `x`. @wadler, I'd suggest to replace:

```agda
subst {x = y} ⊢V (⊢` {x = x} Z) with x ≟ y
... | yes refl        =  weaken ⊢V
... | no  x≢y         =  ⊥-elim (x≢y refl)
```
with
```agda
subst {x = z} ⊢V (⊢` {x = y} Z) with y ≟ z
... | yes refl        =  weaken ⊢V
... | no  y≢z         =  ⊥-elim (y≢z refl)
```
and similarly for other cases.

Furthermore, the prose for the variable case has this:

```
∅ ⊢ V ⦂ B
Γ , y ⦂ B ⊢ ` x ⦂ A
------------------------
Γ ⊢ ` x [ y := V ] ⦂ A
```
where the roles of the `A` and `B` types have been swapped compared to the signature of `subst`. To me that swap requires the reader to keep two different contexts for `A` and `B` simultaneously in their head; while it can stay that way, it is needlessly making it harder to follow what's going on.

I can make a pull request that introduces fresh names in `subst` and the prose following it that will reduce the cognitive load needed to follow the proof and its explanation.
